module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
  },
  extends: ["eslint:recommended"],
  parserOptions: {
    ecmaVersion: "latest",
    sourceType: "module",
  },
  rules: {
    "array-callback-return": ["error", { allowImplicit: false, checkForEach: true }],
    "arrow-body-style": ["error", "as-needed", { requireReturnForObjectLiteral: true }],
    "arrow-parens": ["error", "always"],
    curly: ["error", "all"],
    "default-case-last": "error",
    "dot-notation": "error",
    eqeqeq: ["error", "always", { null: "ignore" }],
    "grouped-accessor-pairs": ["error", "getBeforeSet"],
    "logical-assignment-operators": ["error", "always", { enforceForIfStatements: true }],
    "max-len": [
      "warn",
      {
        code: 100,
        ignoreUrls: true,
        ignorePattern: "const .+ = require\\(",
        ignoreComments: true,
      },
    ],
    "new-cap": ["error", { properties: false }],
    "no-alert": "warn",
    "no-console": ["warn", { allow: ["warn", "error", "info"] }],
    "no-constant-binary-expression": "error",
    "no-constructor-return": "error",
    "no-duplicate-imports": ["error", { includeExports: true }],
    //"no-else-return": ["error", { allowElseIf: false }],
    "no-empty": ["error", { allowEmptyCatch: true }],
    "no-empty-function": ["error", { allow: ["arrowFunctions"] }],
    "no-implicit-coercion": ["error", { allow: ["!!"] }],
    "no-implied-eval": "error",
    "no-invalid-this": "error",
    "no-lone-blocks": "error",
    // "no-lonely-if": "error",
    "no-loss-of-precision": "error",
    "no-multi-spaces": ["error", { ignoreEOLComments: false }],
    "no-new-wrappers": "error",
    "no-param-reassign": ["error", { props: true }],
    "no-promise-executor-return": "error",
    "no-return-assign": ["error", "always"],
    // "no-template-curly-in-string": "error",
    "no-throw-literal": "error",
    "no-trailing-spaces": "error",
    "no-unmodified-loop-condition": "error",
    "no-unreachable-loop": "error",
    "no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
    "no-unused-expressions": [
      "error",
      {
        allowShortCircuit: false,
        allowTernary: false,
        allowTaggedTemplates: false,
      },
    ],
    "no-unused-vars": ["error", { args: "none", ignoreRestSiblings: true }],
    "no-use-before-define": ["error", { functions: false, classes: true, variables: true }],
    "no-useless-return": "error",
    "no-var": "error",
    "object-curly-spacing": ["error", "never"],
    "prefer-arrow-callback": ["error", { allowNamedFunctions: false, allowUnboundThis: true }],
    "prefer-const": ["error", { destructuring: "all" }],
    "prefer-destructuring": ["warn", { object: true, array: false }],
    "prefer-numeric-literals": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": ["error", { allowEmptyReject: false }],
    "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
    "prefer-rest-params": "error",
    //"prefer-spread": "error",
    "prefer-template": "error",
    quotes: ["error", "single", { avoidEscape: true, allowTemplateLiterals: true }],
    "require-atomic-updates": "error",
    "require-await": "error",
    semi: ["error", "always"],
    "space-before-function-paren": [
      "error",
      {
        anonymous: "never",
        named: "never",
        asyncArrow: "always",
      },
    ],
    strict: ["error", "global"],
    "symbol-description": "error",
    "wrap-iife": ["error", "inside", { functionPrototypeMethods: true }],
    yoda: ["error", "never"],
  },
};
