#!/usr/bin/env tsx
import {execSync} from 'node:child_process';
import {existsSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkgRoot = dirname(__dirname);
const repoRoot = execSync('git rev-parse --show-toplevel', {encoding: 'utf-8'}).trim();

const GENERATED_HEADER =
  '# GENERATED BY @sonarmd/star-config — edits will be overwritten on next install.';

interface ConfigFile {
  path: string;
  content: string;
}

const files: ConfigFile[] = [
  {
    path: '.gitleaks.toml',
    content: [
      GENERATED_HEADER,
      '# Baseline config ships in @sonarmd/star-config/gitleaks/default.toml.',
      '# CI and local scans load that file via --config; this file simply points at it',
      '# for tooling that auto-discovers .gitleaks.toml at repo root.',
      '',
      '[extend]',
      'path = "node_modules/@sonarmd/star-config/gitleaks/default.toml"',
      '',
    ].join('\n'),
  },
  {
    path: '.semgrepignore',
    content: [
      GENERATED_HEADER,
      '# Mirrors the `paths.exclude` list in the shipped baseline.',
      'node_modules/',
      'dist/',
      'build/',
      '.husky/',
      '.claude/',
      'archive/',
      '**/__tests__/',
      '**/test/',
      '**/tests/',
      '**/fixtures/',
      '**/snapshots/',
      '**/*.snap',
      '',
    ].join('\n'),
  },
  {
    path: '.trivyignore',
    content: [
      GENERATED_HEADER,
      '# One CVE ID per line, optionally followed by an expiration:',
      '#   CVE-2024-1234 exp:2026-12-31',
      '# No IDs ignored by default. Use trivy/config.yaml for severity + unfixed filters.',
      '',
    ].join('\n'),
  },
];

let wrote = 0;
let skipped = 0;
for (const f of files) {
  const dest = join(repoRoot, f.path);
  if (existsSync(dest)) {
    const first = readFileSync(dest, 'utf-8').split('\n', 1)[0];
    if (first !== GENERATED_HEADER) {
      console.log(`star-config: SKIP ${f.path} (exists, not generated by us — leaving alone)`);
      skipped++;
      continue;
    }
  }
  writeFileSync(dest, f.content);
  console.log(`star-config: wrote ${f.path}`);
  wrote++;
}

console.log(`\nstar-config: security configs installed (${wrote} written, ${skipped} skipped)`);
console.log('star-config: CI scans use @sonarmd/star-config/{semgrep,gitleaks,trivy}/* directly.');
console.log(
  'star-config: to run locally: yarn dlx semgrep scan . && yarn dlx gitleaks detect --no-git -v && trivy fs .'
);
